added FP fixes for racy append to slice and map rules
trailofbits/semgrep-rules pull request #37
Opened 2023-10-04 20:17 UTC by hex0punk

Started seeing FPs for cases such as the below for maps or slices, as the rulkes did not make sure that the lock could be called with `defer`

```go
func appendToSlice_FP5() []int {
	// FP: The `append` is done inside a defer lock
	var wg sync.WaitGroup
	var rMut sync.Mutex
	var r []int
	for i := 0; i < 10; i++ {
		wg.Add(1)
		go func(iCpy int) {
			defer wg.Done()
			m := iCpy * 2
			// ok: racy-append-to-slice
			rMut.Lock()
			defer rMut.Unlock()
			r = append(r, m)
		}(i)
	}

	wg.Wait()

	return r
}
```

This PR addresses that.

2023-10-11 19:48 UTC, hex0punk commented
Heads up, this is only failing because the way the GH actions command to run the test is deprecated.

2023-10-12 16:01 UTC, GrosQuildu commented
Hey, sorry for delay, busy week! Gonna look at it tomorrow and fix the GH action

2023-10-13 14:00 UTC, GrosQuildu requested changes
There may be statements between Lock and Unlock that should not be problematic imho. Made commit to fix that. Let me know what you thin about the change, and I can merge if everything is fine.

2023-10-13 14:02 UTC, GrosQuildu approved these changes

2023-10-13 15:55 UTC, merged